# Required:

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_add = '''
let g:coc_global_extensions = [
  \  'coc-explorer'
  \, 'coc-html'
  \, ]
'''
