# Required:

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tomtom/tcomment_vim'
